feeds:
  # Trade Finance & Fintech - Focused sources for Product Marketing
  - name: Finextra
    url: https://www.finextra.com/rss/headlines.aspx
  - name: Trade Finance Global
    url: https://www.tradefinanceglobal.com/feed/
  - name: TLDR Fintech
    url: https://tldr.tech/api/rss/fintech
  
  # Additional sources will be provided by Product Marketing team
