name: Generate AI Newsletter (Draft PR)

on:
  schedule:
    - cron: "0 6 * * 3"         # Wednesdays 07:00 CET (06:00 UTC)
  workflow_dispatch:
    inputs:
      commit_directly:
        description: 'Skip PR and commit directly to current branch'
        required: false
        default: 'false'
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  build-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate newsletter markdown
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/generate.py

      # Option 1: Direct commit (for testing)  
      - name: Commit newsletter directly
        if: ${{ fromJSON(inputs.commit_directly || 'false') == true }}
        run: |
          git config --global user.name "AI Newsletter Bot"
          git config --global user.email "ai-newsletter@actions.github.com"
          git add newsletter/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Add newsletter $(date +%Y-%m-%d)"
            git push
          fi

      # Option 2: Create PR (default for scheduled runs)
      - name: Create PR  
        if: ${{ fromJSON(inputs.commit_directly || 'false') != true }}
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.PR_TOKEN }}     # <— use PAT
          branch: newsletter/draft-${{ github.run_id }}
          delete-branch: true
          title: "AI Newsletter draft – ${{ github.run_id }} [ai-agent]"
          body: |
            Auto-generated draft for review.
            Source: newsletter/<date>.md
            Please verify sources, claims, and CTA.
          commit-message: "chore(newsletter): add draft issue"
          labels: |
            newsletter
            ai
            needs-review
          add-paths: |
            newsletter/**
            sources.yml
            scripts/**

