name: Generate AI Newsletter (Draft PR)

on:
  schedule:
    - cron: "0 7 * * 2"         # Tuesdays 07:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-draft:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Set up pip cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate newsletter markdown
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/generate.py

      # IMPORTANT: use Actions expressions, not shell, for the branch name
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: newsletter/draft-${{ github.run_id }}      # safe, unique branch
          delete-branch: true
          title: "AI Newsletter draft – ${{ github.run_id }} [ai-agent]"
          body: |
            Auto-generated draft for review.
            - Source file: newsletter/<date>.md
            - Please verify sources, claims, and CTA.
          commit-message: "chore(newsletter): add draft issue"
          labels: |
            newsletter
            ai
            needs-review
          add-paths: |
            newsletter/**
            sources.yml
            scripts/**
